server:
  port: 8082

#logging:
 # level:
  #  root: WARN
    # org.springframework.web: INFO
    # org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false

    
    spring:
  datasource:
    url: jdbc:mysql://localhost/contabildb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 1
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
        hbm2ddl:
          import_files: